Jtso/ontology
Labelbox/labelbox-python pull request #118
Opened 2021-03-10 04:54 UTC by jtsodapop

files written under pep8 via yapf format updating

ontology_generator classes moved to ontology file

ontology tests updated and tested to all pass 

<img width="694" alt="Screen Shot 2021-03-09 at 8 54 06 PM" src="https://user-images.githubusercontent.com/67922677/110578401-980bae80-8119-11eb-92cb-5b8df8b74897.png">

2021-03-10 15:02 UTC, msokoloff1 requested changes
Looks pretty solid! I just have a few minor things that I would like to see changed. Also longer term we might want to support type checking. Right now there is still a chance of creating invalid ontologies even if you pass in the required fields.

2021-03-10 15:02 UTC, msokoloff1 commented on labelbox/schema/ontology.py
> +class OntologyBuilder:
Add a docstring to explain what this is and how it should be used. This is super confusing that an ontology is independent of a project yet you can only create one when you setup a project. This is a limitation of the backend but lets just give a little explanation for what this is and how it should be used.

2021-03-10 19:09 UTC, jtsodapop commented on labelbox/schema/ontology.py
> +            feature_schema_id=dictionary["schemaNodeId"])
change dictionary[] to dictionary.get(key) for optional

2021-03-11 16:29 UTC, msokoloff1 approved these changes
LGTM!

2021-03-12 00:23 UTC, merged