[PLT-0] Do not retry 422 errors
Labelbox/labelbox-python pull request #1598
Opened 2024-05-09 21:10 UTC by vbrodsky

QA discovered this issue when try to create a model config with an invalid model id. In this case, the model service return http 422 as follows:
```
[{'message': 'Validation Error', 'locations': [{'line': 2, 'column': 21}], 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'name': 'ApiError', 'url': 'http://lb-model-service-primary/api/v1/model-configs', 'status': 422, 'statusText': 'Unprocessable Entity', 'body': {'message': '1 validation error for Request body -> modelId value is not a valid uuid (type=type_error.uuid)'}, 'request': {'method': 'POST', 'url': '/api/v1/model-configs', 'body': {'modelId': 'invalid_valid_model_id', 'inferenceParams': {'param': 'value'}, 'organizationId': 'cl4ywm5aw00ke077lh4mrgpw5', 'name': 'model_config'}, 'mediaType': 'application/json', 'errors': {'422': 'Validation Error'}}}}, 'path': ['createModelConfig']}]
```

This PR remove http 422 errors from retrying. 

Also see https://labelbox.atlassian.net/browse/PLT-773?focusedCommentId=201400 for more

2024-05-09 21:36 UTC, adrian-chang approved these changes

2024-05-09 22:25 UTC, adrian-chang requested changes

2024-05-09 22:25 UTC, adrian-chang commented on .github/workflows/python-package-develop.yml
> +    permissions:
Val this should be moved from the previous lines,

Need to add the permission I mentioned on slack here as an addition

2024-05-10 18:44 UTC, vbrodsky commented
Done in another PR

2024-05-10 18:44 UTC, closed without merging