PLT-1016 - Add methods for External Workforce management
Labelbox/labelbox-python pull request #1630
Opened 2024-05-24 21:35 UTC by paulnoirel

This PR adds three methods to manage external workforces (aka BPO organizations) from a project, in particular:

```python
project.add_external_workforce(workforce_id)

project.remove_external_workforce(workforce_id)

project.get_external_workforces()
```

All three methods return a list of `ExternalWorkforce` associated with the project at the end of the operation or an empty list.

2024-05-28 03:58 UTC, adrian-chang commented on libs/labelbox/src/labelbox/schema/project.py
> +        mutation = """
Does this require experimental client mode on? Just wondering don't know myself

2024-05-29 23:24 UTC, adrian-chang requested changes
See comments

2024-06-14 21:43 UTC, sfendell-labelbox commented on libs/labelbox/src/labelbox/schema/project.py
> +            raise LabelboxError(f"Can't find External Workforce {workforce_id}")
Change to `ResourceNotFoundError`

2024-06-14 21:43 UTC, sfendell-labelbox commented on libs/labelbox/src/labelbox/schema/project.py
> +            raise LabelboxError(f"Can't find External Workforce {workforce_id}")
Change to `ResourceNotFoundError`

2024-06-14 22:03 UTC, sfendell-labelbox commented on libs/labelbox/tests/integration/test_external_workforce.py
> +from labelbox import Project, ExternalWorkforce
Remove trailing whitespace from this file (we have some throughout the codebase but prefer to not add more, we really should add this to our lint rules)

2024-06-14 22:04 UTC, sfendell-labelbox commented on libs/labelbox/src/labelbox/schema/project.py
> +from labelbox.schema.external_workforce import ExternalWorkforce
Remove trailing whitespace from this file

2024-06-14 22:05 UTC, sfendell-labelbox commented on libs/labelbox/src/labelbox/schema/project.py
> +from labelbox.schema.external_workforce import ExternalWorkforce
Also, I know this is such a nit, but as long as you're editing it...Could you alphabetize this import to match the rest?

2024-06-17 16:18 UTC, vbrodsky commented on libs/labelbox/tests/integration/test_external_workforce.py
> +    if os.environ['LABELBOX_TEST_ENVIRON'] == "staging":
what is the meaning of this? can you add comments?

2024-07-02 16:29 UTC, lnash4 requested changes
so per @manuaero 's request we would not like to use the add and remove endpoints anymore, now that we have built boost requests within the product 

the mutation's name is upsertProjectBoostWorkforce, this will automatically add the alignerr org as an external workforce

then if the project is properly set up, which means they have 

1. ontology configured 
2. data added
3. there are labeling instructions for the ontology

then you can move the project to the 'REQUESTED' status with the 
updateProjectBoostWorkforceStatus mutation

2024-07-25 13:49 UTC, lb-pno commented
I am closing the current PR since it is not relevant with Alignerr.

2024-07-25 13:49 UTC, closed without merging