[MODEL-1474] Quality modes as list
Labelbox/labelbox-python pull request #1683
Opened 2024-06-19 13:46 UTC by kozikkamil

# Description

Allow creation of projects as both benchmark and consensus. Can only be rolled out after B&C GA.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document change (fix typo or modifying any markdown files, code comments or anything in the examples folder only)

## All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you provided a description?
- [ ] Are your changes properly formatted?

## New Feature Submissions

- [ ] Does your submission pass tests?
- [ ] Have you added thorough tests for your new feature?
- [ ] Have you commented your code, particularly in hard-to-understand areas?
- [ ] Have you added a Docstring?

## Changes to Core Features

- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully run tests with your changes locally?
- [ ] Have you updated any code comments, as applicable?

2024-07-03 18:15 UTC, vbrodsky requested changes
I think making queue_mode from QualityModel to List[...] makes it incompatible for sdk users. You need to be able to take in either one or the whole list

2024-07-05 13:37 UTC, vbrodsky submitted a review, later dismissed

2024-07-05 13:37 UTC, vbrodsky commented on examples/project_configuration/project_setup.ipynb
> +      "source": "batch_project = client.create_project(\n    name=\"Project Setup Demo\",\n    quality_modes=[QualityMode.Consensus\n                  ],  # For benchmarks use quality_mode = QualityM
nice you did it

2024-07-05 13:37 UTC, vbrodsky commented on libs/labelbox/src/labelbox/client.py
>              quality_mode (Optional[QualityMode]): The quality mode to use (e.g. Benchmark, Consensus). Defaults to
can we document that this attr will be deprecated in a future version. And also print a deprecation version if this attr is used

2024-07-05 13:37 UTC, vbrodsky commented on libs/labelbox/src/labelbox/client.py
> +        if quality_modes is None or quality_modes == [QualityMode.Benchmark] or quality_mode is QualityMode.Benchmark:
```suggestion
        if quality_modes is None or len(quality_modes) == 0 or quality_modes == [QualityMode.Benchmark] or quality_mode is QualityMode.Benchmark:
```

2024-07-11 13:52 UTC, vbrodsky submitted a review, later dismissed

2024-07-23 17:27 UTC, vbrodsky reviewed
Left two comments for what I see as improvements, let me know what you think
Also are you planning to update sdk integration tests now or in the future

2024-07-23 17:27 UTC, vbrodsky commented on libs/labelbox/src/labelbox/client.py
> +            quality_modes (Optional[List[QualityMode]]): The quality modes to use (e.g. Benchmark, Consensus). Defaults to
looking at the code below, wondering whether this should be a Set, not a List

2024-07-23 17:27 UTC, vbrodsky commented on libs/labelbox/src/labelbox/client.py
> +        elif quality_modes == [QualityMode.Consensus] or quality_mode is QualityMode.Consensus:
perhaps we could wrap `quality_mode` in a List to make this code cleaner

2024-07-23 17:43 UTC, kozikkamil commented on libs/labelbox/src/labelbox/client.py
> +            quality_modes (Optional[List[QualityMode]]): The quality modes to use (e.g. Benchmark, Consensus). Defaults to
Changed the code to accept either a list or a set, casting to set eventually

2024-07-24 16:47 UTC, vbrodsky submitted a review, later dismissed

2024-07-24 17:17 UTC, vbrodsky approved these changes

2024-07-24 17:17 UTC, merged