[PLT-0]Build test-py-pi for a dev merge even if tests fail
Labelbox/labelbox-python pull request #1774
Opened 2024-08-21 21:12 UTC by vbrodsky

# Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Document change (fix typo or modifying any markdown files, code comments or anything in the examples folder only)

## All Submissions

- [ ] Have you followed the guidelines in our Contributing document?
- [ ] Have you provided a description?
- [ ] Are your changes properly formatted?

## New Feature Submissions

- [ ] Does your submission pass tests?
- [ ] Have you added thorough tests for your new feature?
- [ ] Have you commented your code, particularly in hard-to-understand areas?
- [ ] Have you added a Docstring?

## Changes to Core Features

- [ ] Have you written new tests for your core changes, as applicable?
- [ ] Have you successfully run tests with your changes locally?
- [ ] Have you updated any code comments, as applicable?

2024-08-21 21:48 UTC, adrian-chang commented on .github/workflows/python-package-develop.yml
>      needs: ['build']
needs: ['path-filter']

2024-08-21 21:49 UTC, adrian-chang requested changes
Also, make test-container only depend on needs: ['path-filter'] and not on tests

2024-08-21 21:49 UTC, adrian-chang commented on .github/workflows/python-package-develop.yml
>      needs: ['build']
the other change (if etc. continue on error isn't needed)

2024-08-21 21:55 UTC, sfendell-labelbox submitted a review, later dismissed

2024-08-22 01:00 UTC, adrian-chang approved these changes

2024-08-22 01:00 UTC, merged