[PLT-1392] [PLT-1350] Remove SDK methods for exports v1
Labelbox/labelbox-python pull request #1800
Opened 2024-09-10 02:30 UTC by tomislav-peharda

2024-09-10 17:08 UTC, vbrodsky approved these changes

2024-09-10 22:55 UTC, vbrodsky requested changes
@tomislav-peharda I think Project label_generator() ought to be removed, it uses the methods you have deleted behind scenes

2024-09-11 21:21 UTC, vbrodsky approved these changes

2024-09-11 21:46 UTC, adrian-chang approved these changes

2024-09-11 21:50 UTC, merged