[AL-1283] Merge Label Generator and Video Label Generator
Labelbox/labelbox-python pull request #463
Opened 2022-03-02 15:36 UTC by jtsodapop

This will need to follow standard deprecation procedure once approved.

Calling project.label_generator() will now determine the type of labels and provide either video, or image/text. Mixed data types will still need to use project.export_labels()

2022-03-02 19:05 UTC, msokoloff1 commented on labelbox/schema/project.py
> +        if len(is_video) and not all(is_video) and any(is_video):
This condition is off.

2022-03-02 19:06 UTC, msokoloff1 requested changes
looks good. just one thing to prevent breaking changes

2022-03-02 21:44 UTC, jtsodapop commented
Reaching out to Alex on setting up a deprecation doc, will update this and the AL ticket shortly after

2022-03-16 14:52 UTC, msokoloff1 approved these changes
LGTM

2022-03-16 14:56 UTC, merged