Removed output for tutorials, added a subclasses tutorial
Labelbox/labelbox-python pull request #525
Opened 2022-03-30 14:55 UTC by raphaeljafriLB

2022-03-31 20:49 UTC, jtsodapop requested changes

2022-03-31 20:49 UTC, jtsodapop commented on examples/README.md
> +| Subclasses                   | [Github](annotation_import/subclasses.ipynb)             | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.
can you remove this from the readme?

2022-03-31 22:54 UTC, raphaeljafriLB commented on examples/README.md
> +| Subclasses                   | [Github](annotation_import/subclasses.ipynb)             | [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.
Done!

2022-04-11 14:04 UTC, jtsodapop commented
Closing this out since these changes were pushed in a different pr, spoke with Raph on this already

2022-04-11 14:04 UTC, closed without merging